services:

  postgres:
    image: postgres:15
    container_name: cloudshop-postgres

    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql

    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"
        ]
      interval: 10s
      timeout: 5s
      retries: 5

    networks:
      - cloudshop-network


  backend:
    build:
      context: ./backend

    container_name: cloudshop-backend

    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}

    ports:
      - "5000:5000"

    depends_on:
      postgres:
        condition: service_healthy

    networks:
      - cloudshop-network


  frontend:
    build:
      context: ./frontend

    container_name: cloudshop-frontend

    environment:
      VITE_API_URL: ${VITE_API_URL}

    ports:
      - "5173:5173"

    depends_on:
      - backend

    networks:
      - cloudshop-network


volumes:
  postgres_data:


networks:
  cloudshop-network:
    driver: bridge
